### ISSUE TITLE
Feature request:  make plugin work in neovim

### ISSUE THREAD

**Issue by dewoller** [mipmip/vim-scimark#1]
Plugin looks great!  Very functional, pure markdown tables are painful. 

When I try to get this to work in Neovim, I get the following error:

```
Error detected while processing function OpenInScim:
line   32:
E117: Unknown function: term_start
Press ENTER or type command to continue
```

Thanks!

**Comment by mipmip** [comment]
Build in Neovim support. I'm not a regular nvim, but it seems to work.
