### ISSUE TITLE
Latex Tables

### ISSUE THREAD

**Issue by Jab2870** [mipmip/vim-scimark#4]
Hi,
Would you consider adding support for latex tables?

**Comment by mipmip** [comment]
No. Scimark glues Vim and Sc-im together and unfortunately Sc-im cannot import, nor export latex tables.

**Comment by Jab2870** [comment]
Fair enough. The original SC program did support exporting to tex although I can see that sc-im doesn't. However, there is an open issue regarding this very topic. Would you consider adding tex support if / when sc-im add's support for latex tables?

https://github.com/andmarti1424/sc-im/issues/394

**Comment by mipmip** [comment]
Yes I would. I could use it myself.

**Comment by mipmip** [comment]
Is seems to be implemented: https://github.com/andmarti1424/sc-im/issues/394
